### ISSUE TITLE
Use Github CI to release a new version

### ISSUE THREAD

**Issue by nicogodet** [Artelia/Mesh_tools#18]
We can mark this as a very low priority but we can automate the creation of a new version and upload it to the QGIS plugin repo.

On new tag:

- Update and compile trad
- Check metadata.txt (version)
- Create ZIP file and upload it to QGIS repo.

On new PR:

- Black and isort formating ?
- Flake8 check ?
- Some unit test ?

Relevant link:

https://github.com/3liz/lizmap-plugin/tree/master/.github/workflows

**Comment by ccoulet** [comment]
Could be great.
