### ISSUE TITLE
Prevent running mesh quality analysis on non-triangular mesh

### ISSUE THREAD

**Issue by nicogodet** [Artelia/Mesh_tools#24]

**Comment by ccoulet** [comment]
Hi
That's sounds logical but on another side we could imagine it's also possible to have a mesh analysis for non triangular mesh...
According to the actual developement, we should avoid the use of mesh analysis for other kind of mesh but it could be great to indicate that it could be extended to other kind of mesh if some adaptations are done. Then someone interested in a near future could contribute...

**Comment by nicogodet** [comment]
Yeah, it's just to avoid a python error and display a friendly message.

I think it's possible to extend to any kind of mesh but it's not in my plan 😄
