### ISSUE TITLE
Generalization of the plugin for potential other modeling system

### ISSUE THREAD

**Issue by ccoulet** [Artelia/Mesh_tools#5]
Hi
As I'm working on implementation of culverts in another code (which will be similar on entry to Telemac) I'm wondering if we could think to change telemac_tools on Mesh_Layer_Tools and add a capabilities to manage the computation suite (i.e. Telemac and in future other codes) to foster the future évolutions.
As all the management functions are the same and probably the only changes will be in the output formatted file describing the culverts... This will avoid to duplicate the plugin just for another code.

Feel free to give your opinion.

**Comment by daoum** [comment]
Hi,
From our perspective, we don't see the problem of changing the name of the toolkit for more generic ease of use.
But,I will wait the next release to make the change.

**Comment by ccoulet** [comment]
I made the changes in the code in my branch (dev_cct)
I'm not sure what is the best solution for changing the name...
